### ISSUE TITLE
Group common property helpers

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/interactor#1]
While working with interaction page objects, I'm seeing stuff similar to this a lot:

```javascript
hasField = isPresent('input[data-test-field]');
focusField = focusable('input[data-test-field]');
fillField = fillable('input[data-test-field]');
blurField = blurable('input[data-test-field]');
```

What if we simplified that with a single property helper?

```javascript
field = input('input[data-test-field]');
```

That has a predetermined set of properties...

```javascript
page
  .field.focus()
  .field.fill('value')
  .field.blur()
```

We could do something similar with other properties as well.

```javascript
error = element('[data-test-error]');
```

...

```javascript
expect(page.error.exists).to.be.true
expect(page.error.text).to.equal('some error')
```

And maybe even a way to compose these common properties?

```javascript
field = element('[data-some-thing]').focusable().blurable().fillable()
```

(moved from https://github.com/thefrontside/bigtest/issues/80)

**Comment by wwilsman** [comment]
This can _probably_ be closed with the addition of the `scoped` property creator.

The only additional interactor we might want to add could be used for including other default properties such as `placeholder`, `type`, etc, for inputs. But I can't currently think of other useful default interactors besides `input`.

I'll leave this open for now while we think about a default `input` interactor.

**Comment by Robdel12** [comment]
🤔 How do we feel about this issue now that we're a few months past it?

**Comment by wwilsman** [comment]
I was literally just looking at this minutes ago and debating on closing it. Besides forms, I can't think of other useful interactors to include out-of-box.

Looking back on the idea, I think if we do want common shareable interactors, it could maybe be another package
