### ISSUE TITLE
Add `select`/`selectable` interaction method

### ISSUE THREAD

**Issue by wwilsman** [bigtestjs/interactor#17]
This would work with `<select>` elements by selecting the option containing the _text_.

Currently, we can use `fill`/`fillable` to set the value of a `<select>` element. However, in practice we typically select an option based on it's text value.

The `fill`/`fillable` method does not fail when the value is not present in the list of options, so this can lead to some confusing failed tests. The `select`/`selectable` method should fail when it cannot find the option with the specified text.

**Comment by Robdel12** [comment]
I'm free to pair on this if anyone wants to pick this up & run with it!
