### ISSUE TITLE
Throw better error message when redefining a property

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/interactor#24]
It's not obvious that there are default properties on an interactor like `isVisible`. If you set a property on an interactor with the same key you'll get an error like:

```js
Uncaught Error: cannot redefine existing property "isVisible"
```

In an ideal world we should throw an error saying something like "Interactor already has a property named `isVisible`, please choose a new name"

Or something that says that interactor provides this. I spent ~5 mins looking for a duplicate until I realized what was going on.

**Comment by wwilsman** [comment]
Can this be closed with the updated property name restrictions? Or should we still address the new "reserved property name" error?

**Comment by wwilsman** [comment]
Going to assume this can be closed with the new error

**Comment by Robdel12** [comment]
Yea that makes sense
