### ISSUE TITLE
Helper for checking every member of a collection against a predicate

### ISSUE THREAD

**Issue by Robdel12** [bigtestjs/interactor#3]
It would be nice to have a way to check every member of a collection against a predicate that returns the results `&&`ed together.

Given a collection such:
```
  items = collection($selector, {
    isSelected: hasClass('selected', $child)
  });
```

The ability to add something like the following property would be boss:
```
  allItemsSelected = all(this.items(), item => item.isSelected);
```

(moved from https://github.com/thefrontside/bigtest/issues/65)

**Comment by wwilsman** [comment]
I don't think a helper for this is necessary, and it would get complicated in relation to `this`. 

We could simply use a getter instead :)

``` js
items = collection($selector, {
   isSelected: hasClass('selected', $child)
});

get allItemsSelected() {
   return this.items().every(item => item.isSelected);
}
```
