### ISSUE TITLE
Deprecate `@bigtest/interaction` package

### ISSUE THREAD

**Issue by cowboyd** [bigtestjs/interactor#42]
Originally, the interactors were published under the `@bigtest/interaction` package. 

We accidentally installed it and were . We should probably publish a version with a deprecation message like

"DID YOU MEAN @bigtest/interactor`?

**Comment by Robdel12** [comment]
✅  
![image](https://user-images.githubusercontent.com/2072894/45453776-6f6ce000-b6a7-11e8-91f9-a5c83e9461c3.png)

https://www.npmjs.com/package/@bigtest/interaction

**Comment by cowboyd** [comment]
🤔 can we spit something to the console in a post install hook?

**Comment by Robdel12** [comment]
We would have to release a new package to include a post install script. I think almost 0 people are using it. Plus NPM does throw a warning:
![image](https://user-images.githubusercontent.com/2072894/45455053-6c73ee80-b6ab-11e8-9bd5-e1539bf1fb70.png)
